# Generated by Django 4.2.3 on 2023-07-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

    ]
