# Generated by Django 4.2.11 on 2024-03-19 12:12

from django.db import migrations, models
import django.db.models.deletion
import face_recog.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("face_recog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "CameraNo",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("Location", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("EmpID", models.CharField(default="q", max_length=10)),
                ("FirstName", models.CharField(max_length=255)),
                ("LastName", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("EmpID", models.CharField(default="", max_length=10)),
                ("Name", models.CharField(max_length=255)),
                ("DateTime", models.DateTimeField()),
                (
                    "Image",
                    models.ImageField(upload_to=face_recog.models.image_upload_path),
                ),
                (
                    "CameraNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="face_recog.camera",
                    ),
                ),
            ],
        ),
    ]
